package back.Models;
// Generated Mar 22, 2024 3:54:49 PM by Hibernate Tools 3.5.0.Final

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Acadentunit generated by hbm2java
 */
@Entity
@Table(name = "academicunit", catalog = "auca")
public class Academicunit implements java.io.Serializable {

	private String code;
	private Academicunit academicunit;
	private String name;
	private String eacademicUnit;
	private List<Studentregistration> studentregistrations;
	private List<Course> courses;
	private List<Academicunit> acadentunits;

	public Academicunit() {
	}

	public Academicunit(String code, Academicunit acadentunit, String name, String eacademicUnit) {
		this.code = code;
		this.academicunit = acadentunit;
		this.name = name;
		this.eacademicUnit = eacademicUnit;
	}

	public Academicunit(String code, Academicunit acadentunit, String name, String eacademicUnit,
			List<Studentregistration> studentregistrations, List<Course> courses, List<Academicunit> acadentunits) {
		this.code = code;
		this.academicunit = academicunit;
		this.name = name;
		this.eacademicUnit = eacademicUnit;
		this.studentregistrations = studentregistrations;
		this.courses = courses;
		this.acadentunits = acadentunits;
	}

	@Id

	@Column(name = "code", unique = true, nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parentcode", nullable = false)
	public Academicunit getAcadentunit() {
		return this.academicunit;
	}

	public void setAcadentunit(Academicunit acadentunit) {
		this.academicunit = acadentunit;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "EAcademicUnit", nullable = false, length = 10)
	public String getEacademicUnit() {
		return this.eacademicUnit;
	}

	public void setEacademicUnit(String eacademicUnit) {
		this.eacademicUnit = eacademicUnit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acadentunit")
	public List<Studentregistration> getStudentregistrations() {
		return this.studentregistrations;
	}

	public void setStudentregistrations(List<Studentregistration> studentregistrations) {
		this.studentregistrations = studentregistrations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acadentunit")
	public List<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(List<Course> courses) {
		this.courses = courses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acadentunit")
	public List<Academicunit> getAcadentunits() {
		return this.acadentunits;
	}

	public void setAcadentunits(List<Academicunit> acadentunits) {
		this.acadentunits = acadentunits;
	}

}
