package back.Models;
// Generated Mar 22, 2024 3:54:49 PM by Hibernate Tools 3.5.0.Final

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coursedefinition generated by hbm2java
 */
@Entity
@Table(name = "coursedefinition", catalog = "auca")
public class Coursedefinition implements java.io.Serializable {

	private String code;
	private String name;
	private String description;
	private Integer creadit;
	private List<Course> courses;

	public Coursedefinition() {
	}

	public Coursedefinition(String code, String name, String description) {
		this.code = code;
		this.name = name;
		this.description = description;
	}

	public Coursedefinition(String code, String name, String description, Integer creadit, List<Course> courses) {
		this.code = code;
		this.name = name;
		this.description = description;
		this.creadit = creadit;
		this.courses = courses;
	}

	@Id

	@Column(name = "code", unique = true, nullable = false, length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Creadit")
	public Integer getCreadit() {
		return this.creadit;
	}

	public void setCreadit(Integer creadit) {
		this.creadit = creadit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coursedefinition")
	public List<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(List<Course> courses) {
		this.courses = courses;
	}

}
