package back.Models;
// Generated Mar 22, 2024 3:54:49 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Studentregistration generated by hbm2java
 */
@Entity
@Table(name = "studentregistration", catalog = "auca")
public class Studentregistration implements java.io.Serializable {

	private Integer registartionId;
	private Student student;
	private Semester semester;
	private Academicunit acadentunit;
	private Date registrationDate;
	private List<Studentcourse> studentcourses;

	public Studentregistration() {
	}

	public Studentregistration(Student student, Semester semester, Academicunit acadentunit, Date registrationDate) {
		this.student = student;
		this.semester = semester;
		this.acadentunit = acadentunit;
		this.registrationDate = registrationDate;
	}

	public Studentregistration(Student student, Semester semester, Academicunit acadentunit, Date registrationDate,
			List<Studentcourse> studentcourses) {
		this.student = student;
		this.semester = semester;
		this.acadentunit = acadentunit;
		this.registrationDate = registrationDate;
		this.studentcourses = studentcourses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "registartionId", unique = true, nullable = false)
	public Integer getRegistartionId() {
		return this.registartionId;
	}

	public void setRegistartionId(Integer registartionId) {
		this.registartionId = registartionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "StudentId", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Semester_id", nullable = false)
	public Semester getSemester() {
		return this.semester;
	}

	public void setSemester(Semester semester) {
		this.semester = semester;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Department_code", nullable = false)
	public Academicunit getAcadentunit() {
		return this.acadentunit;
	}

	public void setAcadentunit(Academicunit acadentunit) {
		this.acadentunit = acadentunit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "registrationDate", nullable = false, length = 10)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentregistration")
	public List<Studentcourse> getStudentcourses() {
		return this.studentcourses;
	}

	public void setStudentcourses(List<Studentcourse> studentcourses) {
		this.studentcourses = studentcourses;
	}

}
