package back.Models;
// Generated Mar 22, 2024 3:54:49 PM by Hibernate Tools 3.5.0.Final

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "auca")
public class Student implements java.io.Serializable {

	private String regNo;
	private String firstName;
	private String dateOfBirth;
	private String lastName;
	private List<Studentregistration> studentregistrations;

	public Student() {
	}

	public Student(String regNo, String firstName, String dateOfBirth, String lastName) {
		this.regNo = regNo;
		this.firstName = firstName;
		this.dateOfBirth = dateOfBirth;
		this.lastName = lastName;
	}

	public Student(String regNo, String firstName, String dateOfBirth, String lastName,
			List<Studentregistration> studentregistrations) {
		this.regNo = regNo;
		this.firstName = firstName;
		this.dateOfBirth = dateOfBirth;
		this.lastName = lastName;
		this.studentregistrations = studentregistrations;
	}

	@Id

	@Column(name = "regNo", unique = true, nullable = false, length = 5)
	public String getRegNo() {
		return this.regNo;
	}

	public void setRegNo(String regNo) {
		this.regNo = regNo;
	}

	@Column(name = "firstName", nullable = false, length = 250)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "dateOfBirth", nullable = false, length = 250)
	public String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "lastName", nullable = false, length = 250)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public List<Studentregistration> getStudentregistrations() {
		return this.studentregistrations;
	}

	public void setStudentregistrations(List<Studentregistration> studentregistrations) {
		this.studentregistrations = studentregistrations;
	}

}
