package back.Models;
// Generated Mar 22, 2024 3:54:49 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Studentcourse generated by hbm2java
 */
@Entity
@Table(name = "studentcourse", catalog = "auca")
public class Studentcourse implements java.io.Serializable {

	private String studentCourseId;
	private Course course;
	private Studentregistration studentregistration;
	private Long result;

	public Studentcourse() {
	}

	public Studentcourse(String studentCourseId, Course course, Studentregistration studentregistration) {
		this.studentCourseId = studentCourseId;
		this.course = course;
		this.studentregistration = studentregistration;
	}

	public Studentcourse(String studentCourseId, Course course, Studentregistration studentregistration, Long result) {
		this.studentCourseId = studentCourseId;
		this.course = course;
		this.studentregistration = studentregistration;
		this.result = result;
	}

	@Id

	@Column(name = "StudentCourseId", unique = true, nullable = false, length = 10)
	public String getStudentCourseId() {
		return this.studentCourseId;
	}

	public void setStudentCourseId(String studentCourseId) {
		this.studentCourseId = studentCourseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "registartionId", nullable = false)
	public Studentregistration getStudentregistration() {
		return this.studentregistration;
	}

	public void setStudentregistration(Studentregistration studentregistration) {
		this.studentregistration = studentregistration;
	}

	@Column(name = "Result", precision = 10, scale = 0)
	public Long getResult() {
		return this.result;
	}

	public void setResult(Long result) {
		this.result = result;
	}

}
