package back.Models;
// Generated Mar 22, 2024 3:54:49 PM by Hibernate Tools 3.5.0.Final

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", catalog = "auca")
public class Teacher implements java.io.Serializable {

	private String code;
	private String names;
	private String qualification;
	private String teacherRole;
	private List<Course> courses;

	public Teacher() {
	}

	public Teacher(String code, String names, String qualification, String teacherRole) {
		this.code = code;
		this.names = names;
		this.qualification = qualification;
		this.teacherRole = teacherRole;
	}

	public Teacher(String code, String names, String qualification, String teacherRole, List<Course> courses) {
		this.code = code;
		this.names = names;
		this.qualification = qualification;
		this.teacherRole = teacherRole;
		this.courses = courses;
	}

	@Id

	@Column(name = "code", unique = true, nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "names", nullable = false)
	public String getNames() {
		return this.names;
	}

	public void setNames(String names) {
		this.names = names;
	}

	@Column(name = "Qualification", nullable = false, length = 9)
	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	@Column(name = "TeacherRole", nullable = false, length = 15)
	public String getTeacherRole() {
		return this.teacherRole;
	}

	public void setTeacherRole(String teacherRole) {
		this.teacherRole = teacherRole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teacher")
	public List<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(List<Course> courses) {
		this.courses = courses;
	}

}
